apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-ppdj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-timn-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-ppdj@sha256:0c5a3dd60cd8cb0e10acd02e2f76c47519d9bfba1a310414615464fd831cb262
        name: my-python
        resources: {}
status: {}
